// Code generated by "stringer -type ExitCode exitcode.go"; DO NOT EDIT

package pub

import "fmt"

const _ExitCode_name = "ExitCodeOKExitCodeArgsErrorExitCodeLogSetupErrorExitCodeConfigErrorExitCodeAwsSettingErrorExitCodeLineSettingErrorExitCodeServerStartErrorExitCodeErrorExitCodePanic"

var _ExitCode_index = [...]uint8{0, 10, 27, 48, 67, 90, 114, 138, 151, 164}

func (i ExitCode) String() string {
	i -= 1
	if i < 0 || i >= ExitCode(len(_ExitCode_index)-1) {
		return fmt.Sprintf("ExitCode(%d)", i+1)
	}
	return _ExitCode_name[_ExitCode_index[i]:_ExitCode_index[i+1]]
}
