app_name = "srr-line-pub"
channel_secret = "<Your LINE Channel Secret>"
access_token = "<Your LINE Access Token>"

[server]
host = "example.com"
port = ":8080"

[logger]
filepath = "srr-line-pub.log"
log_level = "debug" # debug, info, warning, error, fatal
