app_name = "srr-line-pub"

[server]
host = "localhost"  # your server
port = ":8080"  # your server port

[logger]
filepath = "srr-line-pub.log" # log file fullpath
log_level = "debug" # debug, info, warning, error, fatal

[aws]
  [aws.sqs]
  region = "ap-northeast-1" # アジアパシフィック (東京)
  queue_url = "【SQSのURL】"

[line]
webhook_url = "【LINEのWebhook URL】"
