[server]
host = "localhost"  # your server
port = ":8080"  # your server port

[logger]
app_name = "srr-line-pub"
filepath = "./srr-line-pub.log" # log file fullpath
log_level = "debug" # debug, info, warning, error, fatal, panic

[aws]
  [aws.sqs]
  region = "ap-northeast-1" # アジアパシフィック (東京)
  endpoint = "localhost" # SQSのエンドポイントURL
  name = "queuename" # SQSのキューの名前

[line]
webhook_url = "/local/path" # LINEのWebhook URL
